#!/bin/bash

cd $HOME/os161
./configure --ostree=$HOME/os161/root --toolprefix=sos-
cd kern/conf
./config ASST2
cd ../compile/ASST2
pmake depend 
pmake
pmake install
cd $HOME/os161/
pmake
pmake install
