#!/bin/bash
cd $HOME/os161
./configure --ostree=$HOME/os161/root --toolprefix=sos-
cd kern/conf
./config ASST0
cd ../compile/ASST0
bmake depend 
bmake
bmake install
cd $HOME/os161/
bmake
bmake install 
cd ~/os161/root
cp ~/sys161/sys161.conf sys161.conf 
cd ~/os161/root
sys161 kernel-ASST0
